### ISSUE TITLE
One Alert on multiple Incident Event 

### ISSUE THREAD

**Issue by Nymeria1** [remg427/TA-thehive#1]
Hello,
First many thanks about this TA.
I have setup the TA alert as Adaptive Response Actions.
When the correlation search run, in TheHive  I see only one alert with reference SPKXXX on multiple events from Splunk.
I would like to see different alert, one on incidents
How I can fix it?

Many thanks for the help

**Comment by Nymeria1** [comment]
For custom alert in the log I see paramater  "unique": "oneEvent".
No evidences from IncidentResponse Action. However the correlation show multiple event with and not same hour.
Below an example about the preview of one alert  in TheHIVE with multiple incident reference.

<img width="115" alt="capture" src="https://user-images.githubusercontent.com/30503052/52070926-36fc6e80-2582-11e9-8adc-a5f4edebdef8.PNG">

**Comment by remg427** [comment]
Hi,
First your search should end with | table field1 field2 etc.
In the action setting, you can mention one field of your search in the input text "unique"
This field is used as a key to group the rows together I.e sharing the same value for this field. 
I am going to double check that the code is correct there.
If you see "oneEvent" it means no field was mentioned so all rows are grouped in a single call / alert

**Comment by Nymeria1** [comment]
Hi remg427.
Yes the search end with you say.
I have set the UniqueID, I am waiting the result. Many thanks.

**Comment by Nymeria1** [comment]
In addition I do not see all fields, indicating in table in my search, in alert preview view in theHive.
 It is configured as Adaptive Response Actions but in detail of Adaptive Response in Incident Response I do not see invocation 
Anyway events are imported in TheHive with issues explained before.
Many thanks

**Comment by Nymeria1** [comment]
Evens imported with unique field are correctly.
Unfortunately not all field are in TheHive

**Comment by remg427** [comment]
I have tested with thehive 3.1.2 and I get the fields into the alert.
I am upgrading to latest and let you know

**Comment by remg427** [comment]
Hello,
I have double checked and the way I built the payload was removing fields with the same value keeping only one.
This now cleaned in v1.04
Could you tell me if you still miss some fields?

**Comment by Nymeria1** [comment]
Ciao,
Many thanks for the update. I have installed and I will give you feedback asap

**Comment by Nymeria1** [comment]
Mant thanks, All fields are now inserted into thehive
