### ISSUE TITLE
Use of TheHive4py

### ISSUE THREAD

**Issue by 0xShiroKuma** [remg427/TA-thehive#10]
Hello Remi,

Could you use the TheHive4py python module to communicate with TheHive's API, instead of using the requests module with hand crafted requests? In order to remain compatible with the API, even if there are changes in TheHive. 

Thanks you!

**Comment by remg427** [comment]
Hello,

Thank you for your question. The reasoning is as follows: Splunk uses Python 2.7 and the scripts are launched by Splunk. Furthermore some people use splunk docker container and do not want to install Python modules via command lines.
When my test env is back live I'll check if thehive4py can work with Python 2.7

Le 3 avril 2019 14:46:31 GMT+02:00, 0xShiroKuma <notifications@github.com> a écrit :
>Hello Remi,
>
>Could you use the TheHive4py python module to communicate with
>TheHive's API, instead of using the requests module with hand crafted
>requests? In order to remain compatible with the API, even if there are
>changes in TheHive. 
>
>Thanks you!
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/TA-thehive/issues/10

-- 
Sent with K-9 Mail.
