### ISSUE TITLE
Add support for an adaptive response action in Splunk Enterprise Security

### ISSUE THREAD

**Issue by xg5-simon** [remg427/TA-thehive#13]
It would be beneficial to add support for an adaptive response action in Splunk Enterprise Security to allow an analyst to selectively create a case or alert in TheHive from the Incident Review dashboard.

If you provide an export from the Add-on builder I can help implement.

**Comment by remg427** [comment]
Hello
I had no time to test 2.0.0 but this built with TA addon builder. 
If you have time to look at it make a PR

**Comment by xg5-simon** [comment]
Hi Remi,

The alert action is available as an adaptive response action in the correlation search editor but not on Incident Review. [Splunk documentation](http://dev.splunk.com/view/enterprise-security/SP-CAAAFBE#adhoc) references that `sendalert` command can be invoked as an ad hoc action and that when creating the alert action to Select the [_Support as an adaptive response action in Splunk Enterprise Security_](http://dev.splunk.com/view/addon-builder/SP-CAAAFBS) checkbox. 

Thanks again for this awesome add-on!

**Comment by traceflow** [comment]
Yes, please!

**Comment by jawaharas** [comment]
Yes please. Same issue here. Can't find the 'The-Hive' alert option in the Incident Reviews' -> 'Adaptive Response Action' section.

**Comment by jawaharas** [comment]
@xg5-simon @tr4cefl0w 
Adding below configuration in **$SPLUNK_HOME/etc/apps/TA-thehive/local/alert_actions.conf** file fixes the issue.

```
[thehive_alert_create_alert]
param._cam = {"supports_adhoc": true}
```

**Comment by remg427** [comment]
Thanks for this,
I'll will merge asap

Le 4 septembre 2019 08:07:33 GMT+02:00, Jass <notifications@github.com> a écrit :
>@xg5-simon @tr4cefl0w 
>Adding below configuration in
>**$SPLUNK_HOME/etc/apps/TA-thehive/local/alert_actions.conf** file
>fixes the issue.
>
>```
>[thehive_alert_create_alert]
>param._cam = {"supports_adhoc": true}
>```
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/TA-thehive/issues/13#issuecomment-527755893

-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
Thanks for this, in $SPLUNK_HOME/etc/apps/TA-thehive/local/alert_actions.conf there is already a stanza

``` 
[create_alert_entry_in_thehive]
param._cam = {"supports_adhoc": true, "technology": [{"vendor": "TheHive-project", "version": ["3.0.0"], "product": "TheHIve"}], "task": ["Investigate"], "subject": ["Alert"], "category": ["Analysis"]}
```

I don't understand why adding another stanza is required as it does not match any script.
Maybe this matches a former script from previous version on your install.

From documentation http://dev.splunk.com/view/enterprise-security/SP-CAAAFBF maybe the following line was missing.
```
command = sendalert $action_name$ results_file="$results.file$" results_link="$results.url$" param.action_name=$action_name$ | stats count
```
I have pushed 2.0.1 and I will try to test it

**Comment by xg5-simon** [comment]
I’ll update and test in the next hour.

**Comment by jawaharas** [comment]
I am using **v1.0.8** of 'TA-thehive' add-on and below configuration works for me.

### Output from 'btool' command:

```
$SPLUNK_HOME/etc/apps/TA-thehive/local/alert_actions.conf      [thehive_alert_create_alert]
$SPLUNK_HOME/etc/system/default/alert_actions.conf             command = sendalert $action_name$ results_file="$results.file$" results_link="$results.url$"
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    description = Create alerts in theHive
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    disabled = 0
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    icon_path = thehive_logo_small.png
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    is_custom = 1
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    label = create THEHIVE alert(s) (alert action)
$SPLUNK_HOME/etc/apps/TA-thehive/local/alert_actions.conf      param._cam = {"supports_adhoc": true}
$SPLUNK_HOME/etc/apps/TA-thehive/default/alert_actions.conf    payload_format = json
```

**Comment by remg427** [comment]
Ah OK it makes sense as this is the name of the alert action in v1.0
V2 has been refactored to have ES adaptative response, encrypted credentials and https only outgoing calls so normally ready for cloud

-- 
Sent with K-9 Mail.

**Comment by xg5-simon** [comment]
Create alert entry in TheHive is available as The Adaptive Response action but I'm getting a "ActiveResponseException: Invalid parameter for adhoc modular action" error when it is run. Anyone else seeing that?

**Comment by jawaharas** [comment]
Yes. I am.

Adding below configuration in 'alert_actions.conf' file fixes the issue.

```
param.caseTemplate =
param.type = alert
param.source = Splunk
param.unique = $user$
param.title = $name$
param.description = $description$ - $user$
param.tags = 
param.severity = 
param.tlp = 
param.thehive_instance =
```

**Comment by xg5-simon** [comment]
@remg427 any chance the update can be pushed to cloud?

**Comment by traceflow** [comment]
It has. Ask Splunk to update it to 2.0.0

**Comment by remg427** [comment]
The issue #19 remains.
Have you users (people who have to set up inputs) the capability "list_storage_passwords"?
this is required to have the page "inputs" loading

**Comment by xg5-simon** [comment]
Confirmed this alert action.conf resolves the mod alert error. 


[create_alert_entry_in_thehive]
is_custom = 1
param._cam = {"supports_adhoc": true, "technology": [{"vendor": "TheHive-project", "version": ["3.0.0"], "product": "TheHive"}], "task": ["Investigate"], "subject": ["Alert"], "category": ["Analysis"]}
description = Create an alert entry in TheHive with all fields attached as observable
label = Create alert entry in TheHive
payload_format = json
icon_path = alert_create_alert_entry_in_thehive.png
command = sendalert $action_name$ results_file="$results.file$" results_link="$results.url$" param.action_name=$action_name$ | stats count
param.th_case_template = default
param.th_type = alert
param.th_source = Splunk
param.th_unique_id = $event_hash$
param.th_title = $name$
param.th_description = $description$ - $user$
param.th_tags = 
param.th_tlp = 2
param.th_severity = 3
param.th_pap = 2
param.th_instance =
