### ISSUE TITLE
Splunk 8.0

### ISSUE THREAD

**Issue by pcyr44** [remg427/TA-thehive#26]
Has anyone had success implementing this on Splunk 8.0.*, I am unable to connect to thehive instance and after enabling debugging the only logs that I can see are just showing "starting new https connection" 3 times per minute.

**Comment by remg427** [comment]
Hello,
I developped it on spkunk 8.0
Which version do you use?
What happens when you create an alert in splunk with an action to push it to thehive?

For the frequency you can set it to 8640000 as this is just use to configure the app

You also can try ta-thehive-ce that does nomore  inputs.conf
-- 
Sent with K-9 Mail.

**Comment by pcyr44** [comment]
I can see no connection with the hive, both firewallD and SELinux are disabled and there are no other firewalls in place between these assets. I was looking to find an error somewhere but the logs show nothing but a connection attempt. Do you have a test alert which can be ran via a search to see if I can narrow it down? Like the MISP integration that you created

**Comment by invinciblehackerrishi** [comment]
I'm using the same app (ta-thehive-ce) but i'm not able to connect splunk with thehive. What are all the configurations need to be done. Can anyone help me on this ?

**Comment by remg427** [comment]
This app allows you to create Splunk alert action to create an alert in the hive.
So make a search that return some data rename the fields to start th_ and followed by the datatype and you should see some alert in splunk
As soon I can I will publish an example with sendalert
-- 
Sent with K-9 Mail.

**Comment by remg427** [comment]
TA-thehive and TA-thehive-ce (Cloud Edition) implement only and alert action to create alerts into TheHive. They don't pull any data from TheHive.
If you have some ideas to extend the features, please create a feature request. I'll try to implment it

**Comment by invinciblehackerrishi** [comment]
I'm just trying to feed the alert from splunk enterprise to TheHive. i'have installed this app and added thehive url into it. i have added some datatypes from the alert to the lookup file but no luck no alert created in TheHive.

**Comment by remg427** [comment]
Have you managed to make it? It works for me on splunk 8.0 (perso instance)
