### ISSUE TITLE
sendalert from search does not work

### ISSUE THREAD

**Issue by ghost** [remg427/TA-thehive#7]
Remi,

  on last version of APP I was able to invoke a sendalert from a search string. I can not do it any more.  Could you tell me what has changed that is not allowing the function?

My search example
```yaml
index==foo field=bar | table yada yada | sendalert thehive_alert_create_alert param.caseTemplate="snowcones" param.tlp="2"
```

Thank you!

**Comment by remg427** [comment]
I'll look asap. I guess other params are mandatory but I need to check and document

Le 25 février 2019 23:40:20 GMT+01:00, RANGERBEE <notifications@github.com> a écrit :
>Remi,
>
>on last version of APP I was able to invoke a sendalert from a search
>string. I can not do it any more.  Could you tell me what has changed
>that is not allowing the function?
>
>My search example
>```yaml
>index==foo field=bar | table yada yada | sendalert
>thehive_alert_create_alert param.caseTemplate="snowcones" param.tlp="2"
>```
>
>Thank you!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remg427/TA-thehive/issues/7

-- 
Sent with K-9 Mail.

**Comment by ghost** [comment]
Thanks, I'll put all the fields in the query to find what works. Will update findings here.

**Comment by ghost** [comment]
AFter filling all the param.fields possible the error code is still error code 1.

![image](https://user-images.githubusercontent.com/15255470/53431493-8e0e2b80-39e8-11e9-9e82-98ac80f7d6c0.png)


any ideas?

**Comment by ghost** [comment]
It works!!  Here is the correct syntax and order::

```yaml
 | sendalert thehive_alert_create_alert param.caseTemplate="FOO" param.severity="1" param.source="splunk" param.title="Barz" param.tlp="2" param.type="alert"
```

**Comment by remg427** [comment]
@RANGERBEE thanks for your support and efforts to find the issue.

Indeed severity must be an integer 1 for Low to 3 for High. in code there is this config_args['severity'] = int(config.get('severity'))

I am not used to this command sendalert (for testing I use the Gui ;-)
Can I use your example to improve the documentation?
